Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO
Gui, Add, Text, y+30, FOO